=== jcorderog/Lenguaje_de_Marcas_DAW/U1: INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/U1_T2/Ej3.dtd
<!ELEMENT beatles (beatle+)>
<!ELEMENT beatle (name)>
<!ELEMENT name (firstname,lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ATTLIST beatle link CDATA #REQUIRED
real CDATA #IMPLIED>

=== jcorderog/Lenguaje_de_Marcas_DAW/U1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/U1_T2/Ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE beatles SYSTEM "Ej3.dtd"> -->

<beatles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ej3.xsd">
    <beatle link="http://www.paulmccartney.com">
        <name>
            <firstname>Paul</firstname>
            <lastname>McCartney</lastname>
        </name>
    </beatle>
    <beatle link="http://www.johnlennon.com">
        <name>
            <firstname>John</firstname>
            <lastname>Lennon</lastname>
        </name>
    </beatle>
    <beatle link="http://www.georgeharrison.com">
        <name>
            <firstname>George</firstname>
            <lastname>Harrison</lastname>
        </name>
    </beatle>
    <beatle link="http://www.ringostarr.com">
        <name>
            <firstname>Ringo</firstname>
            <lastname>Starr</lastname>
        </name>
    </beatle>
    <beatle link="http://www.webucator.com" real="no">
        <name>
            <firstname>Nat</firstname>
            <lastname>Dunn</lastname>
        </name>
    </beatle>
</beatles>
